DROP DATABASE IF EXISTS facedb;
CREATE DATABASE facedb;

USE facedb;

-- Create the table plans.
CREATE TABLE photoLibrary
(
id int NOT NULL AUTO_INCREMENT,
celebName VARCHAR(255) NOT NULL,
photoURL VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);


CREATE TABLE results
(
id int NOT NULL AUTO_INCREMENT,
userName VARCHAR(255) NOT NULL,
bestMatch VARCHAR(255) NOT NULL,
matchScore DECIMAL(10,2) NOT NULL,
PRIMARY KEY (id)
);
