DROP DATABASE IF EXISTS fhlbt0dduah83egm;
CREATE DATABASE fhlbt0dduah83egm;

USE fhlbt0dduah83egm;

-- Create the table plans.
CREATE TABLE photolibraries
(
id int NOT NULL AUTO_INCREMENT,
celebName VARCHAR(255) NOT NULL,
photoURL VARCHAR(255) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
updatedAT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),

PRIMARY KEY (id)
);


