DROP DATABASE IF EXISTS facedb;
CREATE DATABASE facedb;

USE facedb;

-- Create the table plans.
CREATE TABLE photolibraries
(
id int NOT NULL AUTO_INCREMENT,
celebName VARCHAR(255) NOT NULL,
photoURL VARCHAR(255) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
updatedAT TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),

PRIMARY KEY (id)
);


